2021-01-19 08:46:31,262-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 08:49:25,422-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 08:51:38,884-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 08:52:07,123-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 08:53:15,707-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 08:54:10,919-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 08:57:17,862-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 08:58:21,403-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:00:11,594-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:00:40,016-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:02:35,207-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:03:36,131-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:05:51,747-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:06:43,212-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:08:09,676-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:08:50,089-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:18:20,209-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:19:10,475-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:19:41,576-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:25:03,713-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 09:32:26,427-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:37:19,580-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:40:50,567-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:44:00,139-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:46:43,098-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:51:25,479-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:53:26,810-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:54:25,274-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 10:55:07,975-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:01:50,839-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:10:07,871-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:21:28,939-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:22:22,473-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:22:57,385-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 11:23:27,235-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:25:35,013-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:27:44,135-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:31:24,880-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:39:12,627-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:43:04,673-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:44:38,112-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 11:46:17,780-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:47:48,382-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 11:49:05,606-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:50:37,687-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 11:53:46,560-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 11:55:16,773-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 14:07:41,602-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:09:14,204-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 14:11:22,497-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:12:44,302-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:13:29,226-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:14:28,083-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:34:10,061-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:34:39,474-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 14:35:14,676-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:36:45,740-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 14:47:56,167-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:49:28,653-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 14:50:09,101-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:51:39,837-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 14:55:39,179-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:57:06,591-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:57:35,878-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 14:57:54,735-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 14:59:23,281-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:01:56,073-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 15:03:25,268-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:06:03,112-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 15:07:31,328-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:08:48,955-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:10:38,123-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 15:12:10,179-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:12:32,042-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:12:58,862-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:13:25,179-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:13:48,680-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 15:15:16,019-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:15:36,706-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:16:03,198-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:16:30,284-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:16:57,440-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:17:18,037-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 15:18:46,206-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:20:11,290-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:21:54,640-E:\software\Python3.8.3\UiAuto\common\run_case.py-[line:75]-40-find_case-ERROR-message:文件类型是：备份,不是用例文件!
2021-01-19 15:23:22,581-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

2021-01-19 15:24:41,401-E:\software\Python3.8.3\UiAuto\common\general.py-[line:153]-40-element-ERROR-message:Message: 

